### ISSUE TITLE
Change the default email address

### ISSUE THREAD

**Issue by ctbur** [armory/dinghy#110]
If the owner's email address is not set in the dinghyfile, dinghy will choose `unknown@unknown.com`: https://github.com/armory/dinghy/blob/53e40fda7feb4a87591524c87bc4d863507ab246/pkg/dinghyfile/builder.go#L108
The domain unknown.com is registered and emails sent to the address could potentially leak data. Would it be possible to change the default email address to something invalid, e.g., just `-`?

FYI: I would have opened a PR directly, but it seems you are using a special PR format and there is no `CONTRIBUTING.md` to explain it.

**Comment by Jossuecito** [comment]
Thanks for your finding!! We changed the default email address to unknown@example.org, as per IANA this is an example domain and is not available for registration or transfer.
