### ISSUE TITLE
How to reference local modules

### ISSUE THREAD

**Issue by billiford** [armory/dinghy#87]
The example in this repo found [here](https://github.com/armory/dinghy/blob/master/example/dinghyfile) seems to reference local modules not stored in an external repo. Is this possible?

I tried adding the `type Variable` and `func module` declarations but I'm still getting
```
Dinghy Failed Update: path/to/dinghyfile (invalid character 't' after top-level value)
```

Without those declarations I get a 404 on our module repo since those modules don't exist. I would like to keep them local.

**Comment by Jossuecito** [comment]
Hi!

Let me take a look at that sample, I will reply ASAP with a more concrete example for that. Current dinghy documentation can be found at:
https://docs.armory.io/spinnaker/using_dinghy/

There is project that enables you to test dinghyfiles in your local:
https://github.com/armory-io/arm

This project enables you to render dinghyfiles in your local, the modules repo can be simulated as a folder. You can do:

`go run main.go dinghy render --help` to get the help


```
render a dinghyfile

Usage:
  arm dinghy render [dinghyfile] [flags]

Flags:
  -h, --help             help for render
      --modules string   local path to the dinghy modules repository
      --rawdata string   optional rawdata json in case is needed

Global Flags:
  -l, --loglevel string   log level (default "info")
```

**Comment by akshayabd** [comment]
Hi @billiford, thanks for bringing up that example - we're going to update it and remove the local functions being used as modules - its not a use-case we want to encourage/support.

As @Jossuecito mentioned you can use ARM CLI with the --modules to debug locally. We are focusing on updating ARM CLI a lot in our current sprint, @Jossuecito *just* updated ARM CLI with numerous improvements, and we're working on a few more (such as actual error messages instead of just "nil" output).

**Comment by billiford** [comment]
Thanks for looking into updating the example, that was a little confusing.

When I reference "local" I mean "local to the repo the dinghyfile is in", not on my machine. Let me give you an example of what I'd like to see so I can learn why it isn't possible, or perhaps open a feature request.

I work with dinghyfiles that create several pipelines for Spinnaker. These dinghy files reach thousands of lines, making them more difficult than necessary to work with.

I understand that dinghy looks at an *external* repo for where its modules are defined, and this repo is defined in the `hal` config. 

Instead of having a `module` function that references these modules in a separate github repo, would it be possible to add functionally for a `local_module` function?

Here is my current repo structure for a dinghyfile.

```
.
├── dinghyfile
└── README.md
```

Instead, this is how I would like to organize the project structure.

```
├── dinghyfile
├── modules/
├──── my-pipeline-name/
├────── pipeline.module
├────── stages/
├──────── my-stage-1.module
├──────── my-stage-2.module
└── README.md
```

To me, this would make the dinghyfile much easier to work with and would be a more logical directory structure.

Is this possible within dinghy? If not, could you explain why and close this issue? Otherwise, I can open a feature request.

**Comment by akshayabd** [comment]
Thanks for the explanation, yes please open a feature request. I've created an internal ticket for this as well.

**Comment by billiford** [comment]
feature opened at https://github.com/armory/dinghy/issues/88
